// display-app/src/App.vue
<template>
	<div class="container">
		<h2 v-if="animalVotes.dogs">Dogs: {{ animalVotes.dogs }}</h2>
		<h2 v-if="animalVotes.cats">Cats: {{ animalVotes.cats }}</h2>
	</div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';

import axios from 'axios';

const animalVotes = ref({
	dogs: null,
	cats: null,
});

onMounted(() => {
	getAnimalVotes('dogs');
	getAnimalVotes('cats');
});

const getAnimalVotes = async (animal: string): Promise<void> => {
	const response = await axios.get(`http://localhost:8001/data/${animal}`);

	animalVotes.value[animal] = response.data.value;
};
</script>

<style scoped>
.container {
	display: flex;
	gap: 1rem;
	align-items: center;
	justify-content: center;
}
</style>

// voting-app/src/App.tsx
import { useEffect } from 'react';

import axios from 'axios';

import './App.css';

function App() {
	useEffect(() => {
		async function getRedisData() {
			const response = await axios.get('http://localhost:8001/data');

			return response;
		}

		getRedisData();
	}, []);

	const voteDogs = async () => {
		const response = await axios.post('http://localhost:8001/data', {
			key: 'dogs',
			value: 3,
		});

		console.log(response);
	};

	return (
		<>
			<h1>Choose between:</h1>
			<div className="btn-container">
				<button onClick={voteDogs}>Dogs</button>
				<button>Cats</button>
			</div>
		</>
	);
}

export default App;
